### ISSUE TITLE
Contato via discord

### ISSUE THREAD

**Issue by ExBitchss** [b1scoito/external#27]
opa mano consegue enviar seu discord pra nois trocar um papo? se conseguir agradeco desde ja

ou se nao conseguir enviar pelo github msm aq adicione-me pelo meu discord abaixo.
  |
  |
 V
ExBitchss#7357

**Comment by x55ch** [comment]
opa mano consegue enviar seu discord pra nois trocar um papo? se conseguir agradeco desde ja

ou se nao conseguir enviar pelo github msm aq adicione-me pelo meu discord abaixo.
|
|
V
ExBitchss#7357

**Comment by b1scoito** [comment]
Favor me mandar um e-mail em: eu@biscoito.eu
